name: rad_video_player
description: Flutter plugin for displaying inline video with other Flutter
  widgets on Android, iOS, and web.
repository: https://github.com/radocc/rad_video_player
version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.radocc.plugins.videoplayer
        pluginClass: VideoPlayerPlugin

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.3.0
  rad_video_player_platform_interface:
    git: 
      url: https://github.com/radocc/rad_video_player_platform_interface.git
      ref: main
  # The design on https://flutter.dev/go/federated-plugins was to leave
  # this constraint as "any". We cannot do it right now as it fails pub publish
  # validation, so we set a ^ constraint. The exact value doesn't matter since
  # the constraints on the interface pins it.
  # TODO(amirh): Revisit this (either update this part in the design or the pub tool).
  # https://github.com/flutter/flutter/issues/46264


dev_dependencies:
  pedantic: ^1.10.0
  pigeon: ^0.1.21
